name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Package Shared for Nuget
      run: dotnet pack -c Release -o . Valour/Shared/Valour.Shared.csproj
    - name: Publish Shared for Nuget
      run: dotnet nuget push Valour/Shared/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      
    - name: Package Api for Nuget
      run: dotnet pack -c Release -o . Valour/API/Valour.Api.csproj
    - name: Publish Api for Nuget
      run: dotnet nuget push Valour/API/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json    
