name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
    - name: Publish Shared Nuget Package
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Valour/Shared/Valour.Shared.csproj
        VERSION_FILE_PATH: Valour/Shared/Valour.Shared.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish API Nuget Package
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Valour/API/Valour.Api.csproj
        VERSION_FILE_PATH: Valour/Shared/Valour.Shared.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
